/**:
  ros__parameters:
    # There is another set of same parameters in vesc_config.param.yaml,
    # which should be changed at the same time.
    odom_frame: "odom"
    base_frame: "base_link"
    speed_to_erpm_gain: 1900.0
    speed_to_erpm_offset: 0.0
    use_servo_cmd_to_calc_angular_velocity: true
    steering_angle_to_servo_gain: 0.567
    steering_angle_to_servo_offset: 0.47
    wheelbase: 0.3175
    publish_tf: false
